### ISSUE TITLE
Uncaught (in promise) Error: start thumb value must be <= end thumb value

### ISSUE THREAD

**Issue by James103** [TrueBrain/TrueGRF#21]
I get the following error when selecting certain cargoes:
```
Uncaught (in promise) Error: start thumb value (100) must be <= end thumb value (60)
    at e.setValueStart (vendor-62c1be6e.js:931)
    at Object.n.$$.update (vendor-62c1be6e.js:931)
    at sa (vendor-62c1be6e.js:1)
    at Xi (vendor-62c1be6e.js:1)
```

To reproduce,
1. Open https://truebrain.github.io/TrueGRF/
2. Click on Category and select Cargoes.
3. Click on Coal or some of the other cargoes until the app stops responding.
4. Notice the error in the console.

**Comment by TrueBrain** [comment]
Thank you so much for reporting this :D

It is an issue with an external component; yesterday I upstreamed a fix for it, and now I am waiting for the author to merge it. Sadly, I cannot fix this issue in my code, so I am afraid we are left waiting till upstream fixes it. So far, from what I have seen, he is pretty responsive :)

Will update when the fix lands in TrueGRF :)

**Comment by James103** [comment]
> It is an issue with an external component; yesterday I upstreamed a fix for it, and now I am waiting for the author to merge it

Which external component and PR do you mean by this?
